# Generated by Django 5.1 on 2025-01-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_flowerstories_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="flowerStories",
            new_name="flower_stories",
        ),
        migrations.AlterModelOptions(
            name="flower_stories",
            options={"verbose_name_plural": "Flower Stories"},
        ),
    ]
