# Generated by Django 5.1 on 2025-01-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_rename_flower_stories_flowerstories"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowerstories",
            name="Rurl",
            field=models.CharField(default="hihi", max_length=100),
        ),
    ]
