# Generated by Django 5.1 on 2025-01-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_flowerstories_rurl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowerstories",
            name="Rurl",
        ),
    ]
