# Generated by Django 5.1.3 on 2025-01-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_remove_flowerstories_rurl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="plaintext_password",
        ),
    ]
