# Generated by Django 5.1.3 on 2025-01-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_remove_profile_plaintext_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flower_Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Flower categories",
            },
        ),
    ]
