# Generated by Django 5.1.3 on 2025-01-14 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_flower_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowerstories",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.flower_categories",
            ),
        ),
    ]
